-- Insert catalog categories
INSERT INTO catalog_categories (name, slug, description, image_url, icon_name, specs_summary, sort_order) VALUES
('Автобетононасосы', 'avtobetonanosy', 'Благодаря комплексному повышению эффективности по сравнению с традиционными экскаваторами и таким преимуществам, как надёжность, высокая экономия топлива, простота ремонта, обслуживания и низкая стоимость, автобетононасосы SANY высоко оцениваются клиентами по всему миру.', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9Sz6BVMOq25x4Ea1qYES8uQ2fye5fj.png', 'Truck', 'Высота подачи 33~71 м | Производительность 120~180 м³/ч', 1),
('Автогрейдеры', 'avtogreydery', 'Автогрейдеры для дорожного строительства и планировки территорий', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Qbw4gQ0p05inOnjrK90CTNalGi8nWI.png', 'Construction', 'Мощность 112~176 кВт | 11.6~18.5 тонн', 2),
('Бульдозеры', 'buldozery', 'Гусеничные и колесные бульдозеры для земляных работ', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Qbw4gQ0p05inOnjrK90CTNalGi8nWI.png', 'Tractor', 'Объём отвала 1.24~28 м³ | 7.9~106 тонн', 3),
('Экскаваторы', 'ekskavatory', 'Гусеничные экскаваторы для различных видов работ', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7Ay23jJPKAy4UVd5L7pSbIdJ4c3O50.png', 'Excavator', 'Ковш 0.22~2.2 м³ | 5.9~46.8 тонн', 4),
('Компакторы', 'kompaktory', 'Дорожные катки и компакторы для уплотнения грунта', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Qbw4gQ0p05inOnjrK90CTNalGi8nWI.png', 'Roller', 'Объём 9~12 м³ | 23~28 тонн', 5),
('Трубоукладчики', 'truboukladchiki', 'Специализированная техника для укладки трубопроводов', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Qbw4gQ0p05inOnjrK90CTNalGi8nWI.png', 'Crane', 'Грузоподъемность 25~90 тонн | Мощность 130~235 кВт', 6),
('Дорожные катки', 'dorozhnye-katki', 'Катки для уплотнения асфальта и грунта', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Qbw4gQ0p05inOnjrK90CTNalGi8nWI.png', 'Roller', 'Ширина вальца 1~2.7 м | 2.9~30 тонн', 7),
('Фронтальные погрузчики', 'frontalnye-pogruzchiki', 'Погрузчики для перемещения сыпучих материалов', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Qbw4gQ0p05inOnjrK90CTNalGi8nWI.png', 'Forklift', 'Грузоподъемность 2~7 тонн | Объём ковша 1~5 м³', 8)
ON CONFLICT (slug) DO NOTHING;

-- Insert concrete pump models (Автобетононасосы)
INSERT INTO catalog_models (
  category_id,
  name,
  slug,
  model_code,
  description,
  main_image,
  images,
  working_weight,
  max_reach,
  engine_manufacturer,
  engine_power,
  specifications,
  sort_order
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'avtobetonanosy'),
  'Автобетононасос SANY 33 метра',
  'sany-33-metra',
  'SANY 33',
  'Автобетононасос SANY 33 метра — ваш главный партнер на строительной площадке. Внушительная и надежная машина, созданная для покорения высот.',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9Sz6BVMOq25x4Ea1qYES8uQ2fye5fj.png',
  ARRAY['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9Sz6BVMOq25x4Ea1qYES8uQ2fye5fj.png', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-k0BGTzYBairQP3ZwfaVGppKdghkMKz.png'],
  32000,
  33000,
  'Cummins',
  276,
  '{
    "pump_output": "120 м³/ч",
    "max_pressure": "82 бар",
    "boom_sections": 4,
    "vertical_reach": "32.2 м",
    "horizontal_reach": "28.5 м",
    "concrete_cylinder": "Ø200×1650 мм",
    "hopper_capacity": "500 л",
    "chassis": "SHACMAN",
    "wheelbase": "4600+1350 мм",
    "max_speed": "90 км/ч",
    "fuel_tank": "300 л",
    "hydraulic_tank": "400 л"
  }'::jsonb,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'avtobetonanosy'),
  'Автобетононасос SANY 47 метров',
  'sany-47-metrov',
  'SANY 47',
  'Автобетононасос SANY 47 метров обеспечивает максимальную производительность и дальность подачи бетона для крупных строительных объектов.',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9Sz6BVMOq25x4Ea1qYES8uQ2fye5fj.png',
  ARRAY['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9Sz6BVMOq25x4Ea1qYES8uQ2fye5fj.png'],
  42000,
  47000,
  'Cummins',
  324,
  '{
    "pump_output": "150 м³/ч",
    "max_pressure": "85 бар",
    "boom_sections": 5,
    "vertical_reach": "46.5 м",
    "horizontal_reach": "42.0 м",
    "concrete_cylinder": "Ø230×1800 мм",
    "hopper_capacity": "600 л",
    "chassis": "SHACMAN",
    "wheelbase": "5200+1400 мм",
    "max_speed": "85 км/ч",
    "fuel_tank": "400 л",
    "hydraulic_tank": "500 л"
  }'::jsonb,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'avtobetonanosy'),
  'Автобетононасос SANY 56 метров',
  'sany-56-metrov',
  'SANY 56',
  'Автобетононасос SANY 56 метров — идеальное решение для высотного строительства с максимальной эффективностью.',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9Sz6BVMOq25x4Ea1qYES8uQ2fye5fj.png',
  ARRAY['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-9Sz6BVMOq25x4Ea1qYES8uQ2fye5fj.png'],
  48000,
  56000,
  'Cummins',
  368,
  '{
    "pump_output": "170 м³/ч",
    "max_pressure": "88 бар",
    "boom_sections": 6,
    "vertical_reach": "55.8 м",
    "horizontal_reach": "50.0 м",
    "concrete_cylinder": "Ø260×2000 мм",
    "hopper_capacity": "700 л",
    "chassis": "SHACMAN",
    "wheelbase": "5800+1450 мм",
    "max_speed": "80 км/ч",
    "fuel_tank": "450 л",
    "hydraulic_tank": "550 л"
  }'::jsonb,
  3
);

-- Insert excavator models for the Экскаваторы category
INSERT INTO catalog_models (
  category_id,
  name,
  slug,
  model_code,
  description,
  main_image,
  images,
  working_weight,
  bucket_volume,
  max_digging_depth,
  max_reach,
  engine_manufacturer,
  engine_power,
  engine_model,
  specifications,
  sort_order
) VALUES
(
  (SELECT id FROM catalog_categories WHERE slug = 'ekskavatory'),
  'Гусеничный экскаватор SHANTUI SE150',
  'shantui-se150',
  'SE150',
  'Гусеничный экскаватор SHANTUI SE150 — надежная машина для различных видов земляных работ.',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-k0BGTzYBairQP3ZwfaVGppKdghkMKz.png',
  ARRAY['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-k0BGTzYBairQP3ZwfaVGppKdghkMKz.png', 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-jsZ9h0q8AEf7ekvY2zJpRmGS5E1LlR.png'],
  14500,
  0.65,
  5490,
  8670,
  'Cummins',
  86,
  'QSF3.8T',
  '{
    "operating_weight": "14500 кг",
    "bucket_capacity": "0.65 м³",
    "max_digging_depth": "5490 м",
    "max_digging_reach": "8670 м",
    "max_digging_height": "8495 м",
    "max_dumping_height": "6210 м",
    "ground_pressure": "0.44 кг/см²",
    "engine_manufacturer": "Cummins",
    "engine_model": "QSF3.8T",
    "rated_power": "86 кВт",
    "displacement": "3.76 л",
    "fuel_tank": "245 л",
    "hydraulic_tank": "205 л",
    "travel_speed": "5.2/3.25 км/ч",
    "swing_speed": "12.5 об/мин"
  }'::jsonb,
  1
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'ekskavatory'),
  'Гусеничный экскаватор SHANTUI SE215',
  'shantui-se215',
  'SE215',
  'Гусеничный экскаватор SHANTUI SE215 — мощная машина для тяжелых земляных работ.',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7Ay23jJPKAy4UVd5L7pSbIdJ4c3O50.png',
  ARRAY['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7Ay23jJPKAy4UVd5L7pSbIdJ4c3O50.png'],
  21200,
  0.9,
  6490,
  9870,
  'Cummins',
  124,
  'QSB6.7',
  '{
    "operating_weight": "21200 кг",
    "bucket_capacity": "0.9 м³",
    "max_digging_depth": "6490 м",
    "max_digging_reach": "9870 м",
    "engine_manufacturer": "Cummins",
    "rated_power": "124 кВт"
  }'::jsonb,
  2
),
(
  (SELECT id FROM catalog_categories WHERE slug = 'ekskavatory'),
  'Гусеничный экскаватор SHANTUI SE245LC',
  'shantui-se245lc',
  'SE245LC',
  'Гусеничный экскаватор SHANTUI SE245LC — высокопроизводительная машина для крупных проектов.',
  'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7Ay23jJPKAy4UVd5L7pSbIdJ4c3O50.png',
  ARRAY['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-7Ay23jJPKAy4UVd5L7pSbIdJ4c3O50.png'],
  24800,
  1.8,
  6854,
  10200,
  'Cummins',
  150,
  'QSB6.7',
  '{
    "operating_weight": "24800 кг",
    "bucket_capacity": "1.8 м³",
    "max_digging_depth": "6854 м",
    "max_digging_reach": "10200 м",
    "engine_manufacturer": "Cummins",
    "rated_power": "150 кВт"
  }'::jsonb,
  3
);
